import ThemeProvider from '@/components/common/ThemeProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeToggle } from '@/components/theme/ThemeToggle'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'WYY Next App 网站',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1.0',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning className="h-full">
      <body className={`${inter.className} h-full justify-between flex flex-col`}>
        <ThemeProvider>
          <ThemeToggle />
          {children}
          </ThemeProvider>
      </body>
    </html>
  )
}
